import bcrypt from 'bcrypt'
const data = {
  users: [
    {
      name: "admin",
      email: "admin@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      mobile: 9000000000,
      isAdmin: true,
      isActive: true,
    },
    {
      name: "sai",
      email: "sai@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      mobile: 9000000000,
      isAdmin: false,
      isActive: true,
    },
    {
      name: "sai123",
      email: "sai123@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      mobile: 9000000000,
      isAdmin: false,
      isActive: true,
    },
    {
      name: "sai124",
      email: "sai124@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      mobile: 9000000000,
      isAdmin: false,
      isActive: true,
    },
    {
      name: "user",
      email: "user@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      mobile: 9000000000,
      isAdmin: false,
      isActive: true,
    },
    {
      name: "user1",
      email: "user1@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      mobile: 9000000000,
      isAdmin: false,
      isActive: true,
    },
    {
      name: "user2",
      email: "user2@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      mobile: 9000000000,
      isAdmin: false,
      isActive: true,
    },
  ],

  products: [
    {
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 500,
      countInStock: 10,
      brand: "Nike",
      rating: 4,
      numReviews: 10,
      description: "high quality product",
      seller: "605f595d4dd37320d06d8b37",
    },
    {
      name: "Adidas Fit Shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 600,
      countInStock: 10,
      brand: "Adidas",
      rating: 3.5,
      numReviews: 10,
      description: "high quality product",
      seller: "605f595d4dd37320d06d8b37",
    },
    {
      name: "Lacoste Free Shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 650,
      countInStock: 10,
      brand: "Lacoste",
      rating: 4,
      numReviews: 17,
      description: "high quality product",
      seller: "605f595d4dd37320d06d8b37",
    },
    {
      name: "Nike Slim Pant",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 420,
      countInStock: 10,
      brand: "Nike",
      rating: 2.5,
      numReviews: 14,
      description: "high quality product",
      seller: "605f595d4dd37320d06d8b37",
    },
    {
      name: "Puma Slim Pant",
      category: "Pants",
      image: "/images/p5.jpg",
      price: 400,
      countInStock: 10,
      brand: "Puma",
      rating: 3.5,
      numReviews: 10,
      description: "high quality product",
      seller: "605f595d4dd37320d06d8b38",
    },
    {
      name: "Adidas Fit Pant",
      category: "Pants",
      image: "/images/p6.jpg",
      price: 550,
      countInStock: 0,
      brand: "Adidas",
      rating: 4,
      numReviews: 15,
      description: "high quality product",
      seller: "605f595d4dd37320d06d8b38",
    },
    {
      name: "Real Me SmartPhone",
      category: "Electronics",
      image: "/images/android1.jpg",
      price: 15000,
      countInStock: 0,
      brand: "REALME",
      rating: 4,
      numReviews: 15,
      description: "high quality product",
      seller: "605f595d4dd37320d06d8b38",
    },
    {
      name: "Samsung M20",
      category: "Electronics",
      image: "/images/android2.jpg",
      price: 11000,
      countInStock: 20,
      brand: "SAMSUNG",
      rating: 5,
      numReviews: 15,
      description: "high quality product",
      seller: "605f595d4dd37320d06d8b38",
    },
    {
      name: "Samsung NOTE10",
      category: "Electronics",
      image: "/images/android3.jpg",
      price: 30000,
      countInStock: 20,
      brand: "SAMSUNG",
      rating: 4.8,
      numReviews: 15,
      description: "high quality product",
      seller: "605f595d4dd37320d06d8b39",
    },
    {
      name: "NOKIA N20",
      category: "Electronics",
      image: "/images/android4.jpg",
      price: 10000,
      countInStock: 20,
      brand: "SAMSUNG",
      rating: 2,
      numReviews: 15,
      description: "high quality product",
      seller: "605f595d4dd37320d06d8b39",
    },
    {
      name: "SONY DSLR",
      category: "Electronics",
      image: "/images/camera1.jpg",
      price: 10000,
      countInStock: 20,
      brand: "SONY",
      rating: 3.8,
      numReviews: 15,
      description: "high quality product",
      seller: "605f595d4dd37320d06d8b39",
    },
    {
      name: "CANON DSLR",
      category: "Electronics",
      image: "/images/camera2.jpg",
      price: 10000,
      countInStock: 20,
      brand: "CANON",
      rating: 3,
      numReviews: 15,
      description: "high quality product",
      seller: "605f595d4dd37320d06d8b39",
    },
    {
      name: "BIXY DSLR",
      category: "Electronics",
      image: "/images/camera3.jpg",
      price: 10000,
      countInStock: 20,
      brand: "BIXY",
      rating: 1,
      numReviews: 15,
      description: "high quality product",
      seller: "605f595d4dd37320d06d8b39",
    },
    {
      name: "APPLE DESKTOP",
      category: "Electronics",
      image: "/images/desktop1.jpg",
      price: 10000,
      countInStock: 20,
      brand: "APPLE",
      rating: 4,
      numReviews: 15,
      description: "high quality product",
      seller: "605f595d4dd37320d06d8b38",
    },
    {
      name: "IPHONE 10",
      category: "Electronics",
      image: "/images/iphone1.jpg",
      price: 50000,
      countInStock: 20,
      brand: "APPLE",
      rating: 4,
      numReviews: 15,
      description: "high quality product",
      seller: "605f595d4dd37320d06d8b38",
    },
    {
      name: "IPHONE 11",
      category: "Electronics",
      image: "/images/iphone2.jpg",
      price: 70000,
      countInStock: 20,
      brand: "APPLE",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
      seller: "605f595d4dd37320d06d8b38",
    },
    {
      name: "IPHONE 12 PRO MAX",
      category: "Electronics",
      image: "/images/iphone3.jpg",
      price: 100000,
      countInStock: 20,
      brand: "APPLE",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
      seller: "605f595d4dd37320d06d8b37",
    },
    {
      name: "APPLE MAC PRO",
      category: "Electronics",
      image: "/images/laptop1.jpg",
      price: 80000,
      countInStock: 20,
      brand: "APPLE",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
      seller: "605f595d4dd37320d06d8b37",
    },
    {
      name: "RADIO",
      category: "Electronics",
      image: "/images/radio1.jpg",
      price: 80000,
      countInStock: 20,
      brand: "BULLET",
      rating: 2.5,
      numReviews: 15,
      description: "high quality product",
      seller: "605f595d4dd37320d06d8b37",
    },
    {
      name: "Red Jacket",
      category: "Jackets",
      image: "/images/jacket1.jpg",
      price: 10000,
      countInStock: 20,
      brand: "lorem",
      rating: 3,
      numReviews: 15,
      description: "high quality product",
      seller: "605f595d4dd37320d06d8b37",
    },
    {
      name: "Yellow Jacket",
      category: "Jackets",
      image: "/images/jacket2.jpg",
      price: 20000,
      countInStock: 20,
      brand: "lorem",
      rating: 4,
      numReviews: 15,
      description: "high quality product",
      seller: "605f595d4dd37320d06d8b37",
    },
    {
      name: "BLACK LEATHER SHOES",
      category: "Shoes",
      image: "/images/shoes1.jpg",
      price: 20000,
      countInStock: 20,
      brand: "lorem",
      rating: 4,
      numReviews: 15,
      description: "high quality product",
      seller: "605f595d4dd37320d06d8b37",
    },
    {
      name: "Mad Max Car Toy",
      category: "Toys",
      image: "/images/toys1.jpg",
      price: 1000,
      countInStock: 20,
      brand: "lorem",
      rating: 3,
      numReviews: 15,
      description: "high quality product",
      seller: "605f595d4dd37320d06d8b37",
    },
    {
      name: "Furios Max Car Toy",
      category: "Toys",
      image: "/images/toys2.jpg",
      price: 2000,
      countInStock: 20,
      brand: "lorem",
      rating: 3.5,
      numReviews: 15,
      description: "high quality product",
      seller: "605f595d4dd37320d06d8b38",
    },
    {
      name: "Car Toy",
      category: "Toys",
      image: "/images/toys3.jpg",
      price: 2000,
      countInStock: 20,
      brand: "lorem",
      rating: 5,
      numReviews: 15,
      description: "high quality product",
      seller: "605f595d4dd37320d06d8b38",
    },
    {
      name: "Bouncy Car Toy",
      category: "Toys",
      image: "/images/toys4.jpg",
      price: 2000,
      countInStock: 20,
      brand: "lorem",
      rating: 3.5,
      numReviews: 15,
      description: "high quality product",
      seller: "605f595d4dd37320d06d8b38",
    },
    {
      name: "Yellow Hat",
      category: "Hats",
      image: "/images/hats1.jpg",
      price: 2500,
      countInStock: 20,
      brand: "lorem",
      rating: 2.5,
      numReviews: 15,
      description: "high quality product",
      seller: "605f595d4dd37320d06d8b38",
    },
  ],
};

export default data
