export const USER_REGISTER_REQUEST = "USER_SIGININ_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_REGISTER_FAIL = "USER_SIGININ_FAIL";


export const  USER_SIGNIN_REQUEST = 'USER_SIGININ_REQUEST';
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGININ_FAIL";
export const USER_SIGNOUT = "USER_SIGNOUT";
 